[package]
name = "mangler"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A simple Rust program that mangles and parse C++ symbol names using Itanium ABI."


[dependencies]
pest = "2.7.11"
pest_derive = "2.7.11"
